# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[('MintableToken', 'Mintable Token')], default='MintableToken', max_length=20),
        ),
    ]
