# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_token_token_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='contract_address',
            field=models.CharField(default='0x', max_length=42),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_type',
            field=models.CharField(default='MintableToken', max_length=20),
        ),
    ]
