# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_auto_20170718_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='end_block_offset',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='token',
            name='rate',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='token',
            name='start_block_offset',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
