# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_auto_20170718_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='ico_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='ico_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='phase',
            field=models.CharField(choices=[('PHASE_01', 'Upcoming'), ('PHASE_02', 'Active'), ('PHASE_03', 'Finished')], max_length=8),
        ),
    ]
