# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_auto_20170719_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='cap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='ico_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='ico_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='phase',
            field=models.CharField(blank=True, choices=[('PHASE_01', 'Upcoming'), ('PHASE_02', 'Active'), ('PHASE_03', 'Finished')], max_length=8),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_type',
            field=models.CharField(blank=True, choices=[('TT_01', 'Capped'), ('TT_02', 'Uncapped')], max_length=20),
        ),
    ]
