# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_auto_20170720_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='contract_address',
        ),
    ]
