# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0007_remove_token_contract_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='phase',
        ),
        migrations.AlterField(
            model_name='token',
            name='ico_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='ico_start_date',
            field=models.DateTimeField(),
        ),
    ]
